name: Packa
on: [push]
jobs:
  Fyne-Build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Fyne Install
        run: go get fyne.io/fyne/cmd/fyne
       
      - name: Status Check
        run: echo "Hello World !"

      - run: fyne -v
        
      - name: Fyne Linux Package
        run: fyne package --os linux
        
      - name: Fyne Windows Package
        run: fyne package --os windows
