name: Packa
on: [push]
jobs:
  Fyne-Build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version-file: 'go.mod'
          check-latest: true
          cache: true
          cache-dependency-path: go.sum

      - name: Fyne Install
        run: go install fyne.io/fyne/v2/cmd/fyne@latest
       
      - name: Status Check
        run: echo "Okey..."

      - name: Go Version Check
        run: go version

      - name: Fyne Check
        run: fyne -v

      - name: Fyne Windows Package
        run: fyne package --os windows
        
      - name: Fyne Linux Package
        run: fyne package --os linux
        