name: Packa
on: [push]
jobs:
  Fyne-Build:
    runs-on: windows-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      
      - name: Setup Go Actions
      # You may pin to the exact commit or the version.
      # uses: variantdev/setup-go-actions@6445e1ed59b994c5861125a1e3b8b5c405bcfce2
        uses: variantdev/setup-go-actions@v1
        with:
        # The Go Actions version to download (if necessary) and use. Example: 0.5.10, 0.5, 0.x
          go-actions-version: 0.x

      - name: Fyne Install
        run: go get fyne.io/fyne/cmd/fyne
       
      - name: Status Check
        run: echo "Hello World !"

      - run: fyne -v
        
      - name: Fyne Linux Package
        run: fyne package --os linux
        
      - name: Fyne Windows Package
        run: fyne package --os windows
