name: Packa
on: [push]
jobs:
  Fyne-Build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        
      - name: Fyne İnstall
        run: go install fyne.io/fyne/v2/cmd@latest
      
      - name: Fyne Linux Package
        run: fyne package --os linux
        
      - name: Fyne Windows Package
        run: fyne package --os windows
