name: Packa
on: [push]
jobs:
  Fyne-Build:
    runs-on: windows-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        
      - name: Setup Go Faster
        uses: WillAbides/setup-go-faster@v1.8.0

      - name: Fyne Install
        run: go get fyne.io/fyne/cmd/fyne
       
      - name: Status Check
        run: echo "Hello World !"

      - run: fyne -v
        
      - name: Fyne Linux Package
        run: fyne package --os linux
        
      - name: Fyne Windows Package
        run: fyne package --os windows
